apps/users/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView

app_name = "users"

urlpatterns = [
    path('registro/', views.RegisterUser.as_view(success_url = reverse_lazy('users:registro_completo')), name='registro'),
    path('registro/finalizado', views.RegisterUser.as_view(template_name = "usuario/registroCompleto.html"), name = 'registro_completo'),
    path('login/', LoginView.as_view(template_name='usuario/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='usuario/logout.html'), name='logout'),
    path('EditarUsuario/', views.EditUser.as_view(), name = "editar"),
]

bloggreen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('',views.Inicio, name='inicio'),
    path('',include('apps.users.urls')),
    path('',include('apps.posts.urls')),
    path('perfil/',views.Perfil, name='perfil'),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/usuario/editar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block css %}
    {{ block.super }}
     <link rel="stylesheet" type="text/css" href="{% static 'usuario/css/editar.css' %}">
{% endblock %}

{% block content %}
<div class="container editar mt-5 mb-3 text-white shadow-lg p-3 rounded" >
	<div class="d-flex justify-content-center mb-2 mt-4">
		<h1>EDITAR PERFIL</h1>
	</div>
	<div class="row cuerpo rounded" id="post_contenido">
		<div class="col-12 item">
			<form method="post" class="text-white" enctype="multipart/form-data">
				{% csrf_token %}
				
					<div class="form-row mt-4">
						<div class="form-group col-12">
								{{ form.image|as_crispy_field }}
						</div>
					</div>
					<div class="form-row">
						<div class="form-group col-12">
								{{ form.first_name|as_crispy_field }}
						</div>
					</div>
					<div class="form-row">
						<div class="form-group col-12">
								{{ form.last_name|as_crispy_field }}
						</div>
					</div>
					<div class="form-row">
						<div class="form-group col-12">
								{{ form.email|as_crispy_field }}
						</div>
					</div>
				<button type="submit" class="btn btn-light mt-5 btn-lg btn-block mb-4" value="CREAR POST">MODIFICAR PERFIL</button>   
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/usuario/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
	{{ block.super }}
	<link rel="stylesheet" type="text/css" href="{% static 'usuario/css/login.css' %}">
{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center">
    <div class="row d-inline-flex justify-content-center pt-5 mt-5 mb-5 pe-1" id="container_login">
        <div class="col-lg-6">
            <h2 class="fw-bolder" >Login</h2>
            <form class="form" method="post">{% csrf_token %}
                
            {{ form.as_p }}
                    
                <button class="btn btn-outline-light mt-3" type="submit" id="submit">Ingresar</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/usuario/logout.html
{% extends 'base.html' %}

{% block content %}

Te has Logeado

{% endblock content %}

templates/usuario/perfil.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
	{{ block.super }}
	<link rel="stylesheet" type="text/css" href="{% static 'usuario/css/perfil.css' %}">
{% endblock %}


{% block content %}

	<div class="container cuerpo mt-5 mb-5 text-white shadow-lg p-3 rounded"> 
		<div class="container perfil d-flex justify-content-center text-white ">
			<h2 class="titulo mt-3 mb-4">PERFIL DE USUARIO</h2>
		</div>
		<div class="container descripcion text-white">
            {% if user.image %}
				<img src="{{ user.image.url }}" class="rounded mx-auto d-block img-responsive rounded-circle account-image" id="img_perfil">
			{% else %}
				<img src="{% static 'usuario/imagen/avatar.jpg' %}" class="rounded mx-auto d-block img-responsive rounded-circle account-image" id="img_perfil">
			{% endif %} 
			<br>
			<p class="item d-flex justify-content-center"> Nombre de Usuario <p class="d-flex justify-content-center rounded pt-2 pb-2" style="background-color: #404848"> {{user}} </p> </p>
			<p class="item d-flex justify-content-center"> Nombre <p class="d-flex justify-content-center rounded pt-2 pb-2" style="background-color: #404848"> {{user.first_name}} </p> </p>
			<p class="item d-flex justify-content-center"> Apellido <p class="d-flex justify-content-center rounded pt-2 pb-2" style="background-color: #404848"> {{user.last_name}} </p> </p>
			<p class="item d-flex justify-content-center"> Email <p class="d-flex justify-content-center rounded pt-2 pb-2" style="background-color: #404848"> {{user.email}} </p> </p>
		</div>
		
		<div class="botonmodificar mt-5 d-flex justify-content-center">
			<a href="{% url 'users:editar' %}" class="btn btn-outline-light mt-5 btn-lg btn-block mb-4" >MODIFICAR PERFIL!</a>            
		</div>
	</div>
	
{% endblock %}

templates/usuario/registro.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'usuario/css/registro.css' %}">

<div class="container d-flex justify-content-center"><br>
        <div class="row d-inline-flex justify-content-center pt-3 ms-5 me-5 mb-5 mt-5" id="container_registro">
            <div class="col-lg-6">
                <h2 class="fw-bolder d-flex justify-content-center" >Registro</h2>
                <form class="fw-bold" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    {{ form | crispy }}
                    <br>
                    <div class="d-grid gap-4 d-md-flex justify-content-md-end mt-3">
                        <input class="btn btn-outline-danger" type="reset" value="Borrar">
                        <input class="btn btn-outline-success" type="submit" value="Enviar">
                    </div>
                    <br>
                </form>
            </div>
        </div>
</div>
{% endblock content %}

templates/usuario/registroCompleto.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'usuario/css/registroCompleto.css' %}">
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center mt-5 mb-5" >
    <div class= "container d-flex justify-content-center ms-5 me-5 mt-5 mb-5">
        <div class="ps-4 pe-4 pb-5 pt-5" id="cuadro_Registro">
            <h2>Registro realizado satisfactoriamente.</h2>
            <h2><bold>¡Bienvenido a BlogGreen!</bold></h2>
            <div class="pt-5 pb-3">
                <a class="btn btn-outline-light ps-5 pe-5" href="{% url 'inicio' %}">Inicio</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}