apps/posts/urls.py
from django.urls import path
from apps.posts.views import *

app_name = "posts"

urlpatterns = [
    path('post/crear', PostCreateView.as_view(), name='crearPost'),
    path('post/<int:pk>', PostShowView.as_view(), name='mostrarPost'),
    path('post/editar/<int:pk>', PostEditView.as_view(), name='editarPost'),
    path('post/eliminar/<str:pk>', PostDeleteView.as_view(), name='deletePost'),
    path('post/like/<str:pk>', like_view, name='likesPost'),
    path('post/dislike/<str:pk>', dislike_view, name='dislikesPost'),
    path('post/listar/fecha', PostListView.as_view(), name='listarPost'),
    path('post/<int:pk>/crear_comment/', PostComment.as_view(), name='nuevoComentario'),
    path('busqueda', postSearchView, name = 'buscarPost'),
    path('categoria', postCategoryView, name = 'categoriaPost'),
    path('post/listar/comentario', post_comentarios, name='listarPost2')
]

apps/users/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView

app_name = "users"

urlpatterns = [
    path('registro/', views.RegisterUser.as_view(success_url = reverse_lazy('users:registro_completo')), name='registro'),
    path('registro/finalizado', views.RegisterUser.as_view(template_name = "usuario/registroCompleto.html"), name = 'registro_completo'),
    path('login/', LoginView.as_view(template_name='usuario/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='usuario/logout.html'), name='logout'),
    path('EditarUsuario/', views.EditUser.as_view(), name = "editar"),
]

bloggreen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('',views.Inicio, name='inicio'),
    path('',include('apps.users.urls')),
    path('',include('apps.posts.urls')),
    path('perfil/',views.Perfil, name='perfil'),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        {% block titulo %}
        <title>BlogGreen</title>
        {% endblock %}

        {% block css %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'base/css/base.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@1,500&display=swap" rel="stylesheet">
        {% endblock %}
        <script src="https://kit.fontawesome.com/ce93252b6d.js" crossorigin="anonymous"></script>
    </head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="menu-nav1">
          <div class="pt-2 col-7 d-flex justify-content-end" >
            <a class="navbar-brand d-flex justify-content-start" href="{% url 'inicio' %}" id="titulo-nav">
              <img class="me-4" src="{% static 'base/img/logo.png' %}" id="img-temporal">
              <h2 id="nombreBlog">¡BLOG GREEN!</h2>
            </a>
          </div>
          <form class="ps-5 pe-2 col-5 d-flex justify-content-end">
            <button class="btn btn-outline-success btn-lg" type="submit" href="{% url 'posts:buscarPost' %}?filtro=">Buscar</button>
          </form>
        </nav>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="menu-nav2">
          {% if user.is_authenticated %}  
                <div class="ms-1 me-1 nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'perfil' %}" id="bienvenida"> 
                       Hola {{user.username | upper }}
                    </a>
                </div>
          {% endif %}
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}  

                {% if user.is_superuser %}
                <li class="ms-2 me-2 nav-item">
                    <a class="btn btn-outline-light" href="{% url 'admin:index' %}">Permisos</a>
                </li>
                <li class="ms-2 me-2 nav-item">
                  <a class="btn btn-outline-light" href="{% url 'posts:crearPost' %}">Crear</a>
                </li>
                <li class="ms-2 me-2 nav-item">
                  <a class="btn btn-outline-light" href="{% url 'users:logout' %}">Salir</a>
                </li>
                
                {% elif user.is_writer %}
                <li class="ms-2 me-2 nav-item">
                    <a class="btn btn-outline-light" href="{% url 'posts:crearPost' %}">Crear</a>
                </li>
                <li class="ms-2 me-2 nav-item">
                    <a class="btn btn-outline-light" href="{% url 'users:logout' %}">Salir</a>
                </li>

                {% elif user.is_reader %}
                <li class="ms-2 me-2 nav-item">
                    <a class="btn btn-outline-light ms-auto" href="{% url 'users:logout' %}">Salir</a>
                </li>
                {% endif %}
              
              {% else %}

                <li class="ms-2 me-2 nav-item">
                    <a class="btn btn-outline-light" href="{% url 'users:registro' %}">Registrarse</a>
                </li>
                <li class="ms-2 me-2 nav-item">
                    <a class="btn btn-outline-light" href="{% url 'users:login' %}">Ingresar</a>
                </li>
              
              {% endif %}  

            </ul>
          </div>
        </nav>
    </header>
    <div class="block_contenido">
      {% block content %}
  
      {% endblock content %}
    </div>
    
    <footer class="bg-dark text-center text-white"id='pie_pagina'>
        <!-- Grid container -->
        <div class="container p-4 pb-0">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/informatorio" role="button"
              ><i class="fab fa-facebook-f"></i
            ></a>
      
            <!-- Twitter -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://twitter.com/InformatorioCh" role="button"
              ><i class="fab fa-twitter"></i
            ></a>
      
            <!-- Google -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://empleo.chaco.gob.ar/informatorio#/" role="button"
              ><i class="fab fa-google"></i
            ></a>
      
            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/informatorio/" role="button"
              ><i class="fab fa-instagram"></i
            ></a>
        
            <!-- Linkedin -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/company/informatorio-chaco/" role="button"
              ><i class="fab fa-linkedin-in"></i
            ></a>
      
            <!-- Github -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/Dihue/grupo_13" role="button"
              ><i class="fab fa-github"></i
            ></a>
          </section>
          <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          CONTACTO: grupo13c1@info.com
          <br>
          © 2021 Copyright: Blog Green
        </div>
        <!-- Copyright -->
    </footer>

    {% block js %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% endblock %}

</body>
</html>

templates/buscador.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  {{ block.super }}
   <link rel="stylesheet" type="text/css" href="{% static 'base/css/buscador.css' %}">
{% endblock %}

{% block content %}
<div class="container mb-5">
    <div class="row">
        <div class="col-12">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 search">
                        <div class="text-center">
                            <form method="get">
                                <div id="custom-search-input">
                                    <h4>Ingrese titulo del post a buscar</h5>
                                    <br>
                                    <h5>Ingrese nombre del usuario del creador del post a buscar</h5>
                                    <br>
                                    <div class="mt-2">
                                        <input type="text" class="form-control" placeholder="Buscar..." name="buscar">
                                        <span class="input-group-list">
                                            <i class="icon icon-search"></i>
                                            <div class="text-center">
                                                <button type="submit" class="btn btn-outline-light mt-4">Buscar</button>
                                            </div>
                                        </span>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% if posts %}
                {% for post in posts %}
                    {% if forloop.first%}
                        <div class="row mt-4">
                    {% endif %}

                    <div class="col-4 mb-4">
                        <div class="card">
                            {% if post.thumbnail %}
                                <img class="card-img-top" height="180" src="{{ post.thumbnail.url }}">
                            {% else %}
                                <img src="{% static 'base/img/ciudad.jpg' %}" class="card-img-top" height="180" alt="...">
                            {% endif %}
                            <div class="card-body">
                                <h5 clas="card-title">{{ post.title }}</h5>
                                <h6 class="card-subtitle">Autor: {{ post.user }} </h6>
                                <p class="card-text">Categoría: {{ post.categoria.nombre }} </p>
                                <div class="card-body mt-2 d-flex justify-content-center">
                                    <a href="{% url 'posts:mostrarPost' post.id %}" class="btn btn-primary">Ir al post</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% if forloop.counter|divisibleby:3 %}
                        </div><div class="row">
                    {% endif%}

                    {% if forloop.last %}
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="alert alert-danger mt-4">No hay nada acá</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/index.css' %}">
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'base/js/index.js' %}"></script>
{% endblock %}
<!-- AGREGO EL TITULO DEL TEMPLATE-->

{% block content %}
    <div class="row g-0">
        <div class="col-3 pe-5">
            <nav class="list-group pe-5" id="lista_categorias">
                <a href="{% url 'posts:listarPost' %}" class="list-group-item list-group-item-action d-flex justify-content-center" id="TITULO_ODS">
                    17 ODS
                </a>
                <div name="buscar" id="">
                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods1">Fin de la pobreza</button>
                    <a class="panel" id="but-ods1" href="{% url 'posts:categoriaPost' %}?filtro=1">
                        <img type="submit" src="{% static 'base/img/ODS1.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods2">Hambre cero</button>
                    <a class="panel" id="but-ods2" href="{% url 'posts:categoriaPost' %}?filtro=2">
                        <img src="{% static 'base/img/ODS2.png' %}" alt="">
                    </a>
                    
                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods3">Salud y bienestar</button>
                    <a class="panel" id="but-ods3" href="{% url 'posts:categoriaPost' %}?filtro=3">
                        <img src="{% static 'base/img/ODS3.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods4">Educación de calidad</button>
                    <a class="panel" id="but-ods4" href="{% url 'posts:categoriaPost' %}?filtro=4">
                        <img src="{% static 'base/img/ODS4.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods5">Igualdad de género</button>
                    <a class="panel" id="but-ods5" href="{% url 'posts:categoriaPost' %}?filtro=5">
                        <img src="{% static 'base/img/ODS5.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods6">Agua limpia y saneamiento</button>
                    <a class="panel" id="but-ods6" href="{% url 'posts:categoriaPost' %}?filtro=6">
                        <img src="{% static 'base/img/ODS6.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods7">Energía asequible y no contaminante</button>
                    <a class="panel" id="but-ods7" href="{% url 'posts:categoriaPost' %}?filtro=7">
                        <img src="{% static 'base/img/ODS7.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods8">Trabajo decente y crecimiento económico</button>
                    <a class="panel" id="but-ods8" href="{% url 'posts:categoriaPost' %}?filtro=8">
                        <img src="{% static 'base/img/ODS8.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods9">Industria, innovación e infraestructura</button>
                    <a class="panel" id="but-ods9" href="{% url 'posts:categoriaPost' %}?filtro=9">
                        <img src="{% static 'base/img/ODS9.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods10">Reducción de las desigualdades</button>
                    <a class="panel" id="but-ods10" href="{% url 'posts:categoriaPost' %}?filtro=10">
                        <img src="{% static 'base/img/ODS10.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods11">Ciudades y comunidades sostenibles</button>
                    <a class="panel" id="but-ods11" href="{% url 'posts:categoriaPost' %}?filtro=11">
                        <img src="{% static 'base/img/ODS11.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods12">Producción y consumos responsables</button>
                    <a class="panel" id="but-ods12" href="{% url 'posts:categoriaPost' %}?filtro=12">
                        <img src="{% static 'base/img/ODS12.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods13">Acción por el clima</button>
                    <a class="panel" id="but-ods13" href="{% url 'posts:categoriaPost' %}?filtro=13">
                        <img src="{% static 'base/img/ODS13.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods14">Vida submarina</button>
                    <a class="panel" id="but-ods14" href="{% url 'posts:categoriaPost' %}?filtro=14">
                        <img src="{% static 'base/img/ODS14.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods15">Vida de ecosistemas terrestres</button>
                    <a class="panel" id="but-ods15" href="{% url 'posts:categoriaPost' %}?filtro=15">
                        <img src="{% static 'base/img/ODS15.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods16">Paz, justicia e instituciónes sólidas</button>
                    <a class="panel" id="but-ods16" href="{% url 'posts:categoriaPost' %}?filtro=16">
                        <img src="{% static 'base/img/ODS16.png' %}" alt="">
                    </a>

                    <button class="accordion list-group-item list-group-item-action d-flex justify-content-center" id="but-ods17">Alianzas para lograr los objetivos</button>
                    <a class="panel" id="but-ods17" href="{% url 'posts:categoriaPost' %}?filtro=17">
                        <img src="{% static 'base/img/ODS17.png' %}" alt="">
                    </a>
                </div>
            </nav>  
        </div>
          
        <div class="col-7 pe-5 pt-4" id= "blog_ciudad">
            <div class="pt-5 pe-5" id="blog_ciudad">
                <div class="card" style="background-color: #303535; color: #FFFFFF;">
                    <h4 style="text-align: center;">Ultimo post</h4>
                {% if post %}
                    <div class="">
                        {% if post.thumbnail.url %}
                            <img src="{{ post.thumbnail.url }}" class="card-img-top" alt="...">
                        {% else %}
                            <img src="{% static 'base/img/ciudad.jpg' %}" class="card-img-top" alt="...">
                        {% endif %}
                    </div>
                    <div class="card-body" style="background-color: #303535; color: #FFFFFF;">
                        <h4 class="card-title">{{ post.title }}</h4>
                        <hr>
                        <p class="card-text mt-3">{{ post.content }}</p>
                        <h6 class="card-subtitle">Autor: {{ post.user }} </h6>
                        <p class="card-text">Categoría: {{ post.categoria.nombre }} </p>
                        <p class="card-text">Fecha: {{ post.publish_date }}</p>
                    </div>
                    <div class="card-body mt-2 d-flex justify-content-center" style="background-color: #303535; color: #FFFFFF;">
                        <a href="{% url 'posts:mostrarPost' post.id %}" class="btn btn-primary">Ir al post</a>
                    </div>
                {% else %}
                    <div class="card-body mt-2" style="background-color: #303535; color: #FFFFFF;">
                        <img src="{% static 'base/img/ciudad.jpg' %}" class="card-img-top" alt="...">
                    </div>
                    <div class="card-body" style="background-color: #303535; color: #FFFFFF;">
                        <h3 class="card-title">Titulo de ejemplo</h3>
                        <p class="card-text mt-2" style="background-color: #303535; color: #FFFFFF;">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint fugiat, excepturi, officiis ea animi inventore tempora similique veritatis sapiente eum sequi, ad exercitationem quis dicta. Ex accusantium architecto quisquam totam.</p>
                    </div>
                {% endif %}
                </div>
            </div>
        </div>

        <div class="col-2" style="background: #303535b6; color: #FFFFFF;">
            <div class="">
                <br><br>
                <div class="d-flex justify-content-center">
                    <h2>Menciones:</h2>
                </div>
                <div class="d-flex justify-content-center" >
                    <img class="mt-4 mb-4" style='width: 60%; object-fit: contain;'  src="{% static 'base/img/logoinfo.png' %}" alt="">
                </div>
                <div class="d-flex justify-content-center">
                    <img class="mt-4 mb-4" style='width: 60%; object-fit: contain;' src="{% static 'base/img/UltimoLogoDelChaco.jpg' %}" alt="">
                </div>
                <div class="d-flex justify-content-center">
                    <img class="mt-4 mb-4" style='width: 60%; object-fit: contain;'  src="{% static 'base/img/Logo_Polo_It-06.jpg' %}" alt="">
                </div>
                <div class="d-flex justify-content-center">
                    <img class="mt-4 mb-4" style='width: 60%; object-fit: contain;' src="{% static 'base/img/globant-vector-logo-small.png' %}" alt="">
                </div>

                <div class="mt-5 mb-3">
                    <div class="ps-4">
                        <h3><b> Fundadores:</b></h3>
                    </div>
                    <div class="mt-3">
                        <ul>
                            <h3>Atuel Esperguin</h3>
                            <h3>Dana Erro</h3>
                            <h3>Dihue De Cuadra<h3>
                            <h3>Matias Inglant </h3>
                        </ul>
                    </div>
                </div>
        </div>
    </div>      
{% endblock content %}