apps/posts/urls.py
from django.urls import path
from apps.posts.views import *

app_name = "posts"

urlpatterns = [
    path('post/crear', PostCreateView.as_view(), name='crearPost'),
    path('post/<int:pk>', PostShowView.as_view(), name='mostrarPost'),
    path('post/editar/<int:pk>', PostEditView.as_view(), name='editarPost'),
    path('post/eliminar/<str:pk>', PostDeleteView.as_view(), name='deletePost'),
    path('post/like/<str:pk>', like_view, name='likesPost'),
    path('post/dislike/<str:pk>', dislike_view, name='dislikesPost'),
    path('post/listar/fecha', PostListView.as_view(), name='listarPost'),
    path('post/<int:pk>/crear_comment/', PostComment.as_view(), name='nuevoComentario'),
    path('busqueda', postSearchView, name = 'buscarPost'),
    path('categoria', postCategoryView, name = 'categoriaPost'),
    path('post/listar/comentario', post_comentarios, name='listarPost2')
]

bloggreen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('',views.Inicio, name='inicio'),
    path('',include('apps.users.urls')),
    path('',include('apps.posts.urls')),
    path('perfil/',views.Perfil, name='perfil'),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/posts/models.py
from django.db import models     
from django.conf import settings
from django.core.exceptions import ValidationError

def validar_extension(valor):
	if not valor.name.endswith(settings.ALLOWED_IMG):
		raise ValidationError("Ese formato de imagen no esta permitido.")

class Categoria(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre)

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    thumbnail = models.ImageField(upload_to='post/portada', null=True, blank=False, validators=[validar_extension])
    publish_date = models.DateTimeField(auto_now=True)
    last_updated = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likesPost')
    dislike = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislikesPost')

    categoria = models.ForeignKey(Categoria, null=False, blank=False, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self):
        return '%s - %s - %s' % (self.title, self.categoria, self.user)

    def total_likes(self):
        return self.like.count()
    
    def total_dislikes(self):
        return self.dislike.count()

    @property
    def comments(self):
        return self.comment_set.all()

    @property
    def get_comment_count(self):
        return self.comment_set.all().count()

class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    timestamp = models.DateTimeField(auto_now=True)
    content = models.TextField()

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, blank=False, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, null=True, blank=False, on_delete=models.CASCADE, related_name='commentsPost')

    def __str__(self):
       return '%s - %s - %s - %s' % (self.post.title, self.user, self.id , self.content)

apps/posts/forms.py
from django import forms
from apps.posts.models import Post, Comment
from django.conf import settings

class PostForm(forms.ModelForm):
    class Meta:
        model = Post

        fields = [
            'title',
            'content',
            'thumbnail',
            'categoria',
        ]

        labels = {
            'title': 'Ingrese el titulo'
        }

class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post

        fields = [
            'title',
            'content',
            'thumbnail',
            'categoria',
        ]

class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment

		fields = [
			'content',
		]

apps/posts/views.py
from django.db.models.expressions import OrderBy
from django.http.response import HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls.base import reverse_lazy
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.db.models import Q
from apps.posts.forms import PostForm, EditPostForm, CommentForm
from .models  import Categoria, Post, Comment
from apps.users.models import NewUser
from django.db.models import Count
from django.db.models import F

def like_view(request, pk):
    post = get_object_or_404(Post, id = request.POST.get('post_id'))
    liked = False
    print(post.like.filter(id = request.user.id).exists())

    if post.like.filter(id = request.user.id).exists():
        post.like.remove(request.user)
        liked = False
    else:
        post.like.add(request.user)
        post.dislike.remove(request.user)
        liked = True

    return HttpResponseRedirect(reverse('posts:mostrarPost', args = [str(pk)]))

def dislike_view(request, pk):
    post = get_object_or_404(Post, id = request.POST.get('post_id'))
    disliked = False

    if post.dislike.filter(id = request.user.id).exists():
        post.dislike.remove(request.user)
        disliked = False
    else:
        post.dislike.add(request.user)
        post.like.remove(request.user)
        disliked = True

    return HttpResponseRedirect(reverse('posts:mostrarPost', args = [str(pk)]))

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'post/postForm.html'
    success_url = reverse_lazy('inicio')
    login_url = settings.LOGIN_URL

    def form_valid(self, form):
        form.instance.user = self.request.user

        if form.instance.thumbnail.name:
            ext = form.instance.thumbnail.name.split(".")[-1]
            form.instance.thumbnail.name = form.instance.title + '.' + ext

        return super().form_valid(form)

class PostEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = EditPostForm
    template_name = 'post/postEdit.html'
    success_url = reverse_lazy('inicio')
    login_url = settings.LOGIN_URL

    def form_valid(self, form):
        form.instance.user = self.request.user

        if form.instance.thumbnail.name:
            ext = form.instance.thumbnail.name.split(".")[-1]
            form.instance.thumbnail.name = form.instance.title + '.' + ext

        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.user
            

class MsjException(Exception):
    pass


def like_view(request, pk):
    post = get_object_or_404(Post, id= request.POST.get('post_id'))
    liked = False
class PostListView(ListView):
    model = Post
    ordering = ['-publish_date']
    template_name = 'post/postList.html'
    context_object_name = 'posts'
    
def post_comentarios(request):
    opcion = request.GET.get('select')
    posts = Post.objects.annotate(num_comments=Count('commentsPost')).order_by('-num_comments')

    return render(request,'post/postList.html', {'posts':posts})

class PostShowView(DetailView):
    model = Post
    template_name = 'post/postShow.html'

    def getContextData(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        stuff = get_object_or_404(Post,id=self.kwargs['pk'])
        total_likes = stuff.total_likes()
        total_dislikes = stuff.total_dislikes()

        liked = False
        disliked = False
        if stuff.like.filter(id = self.request.user.id).exists():
            liked = True
        elif stuff.dislike.filter(id = self.request.user.id).exists():
            disliked = True

        context['total_likes'] = total_likes
        context['total_dislikes'] = total_dislikes
        context['liked'] = liked
        context['disliked'] = disliked

        return context  

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('inicio')

class PostComment(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'post/postCommentForm.html'
    success_url = reverse_lazy('inicio')
    login_url = settings.LOGIN_URL

    def form_valid(self, form):
        new = form.save(commit = False)
        new.post_id = self.kwargs['pk']
        new.user = self.request.user
        new.save()

        return HttpResponseRedirect(reverse('posts:mostrarPost', args = [str(new.post_id)]))

#-------------------------------BUSCADOR----------------------------------------------------------

def search(request):
    return render(request, 'buscador.html')

def postSearchView(request):
    queryset = request.GET.get("buscar")

    resultados = {}
    categorias = Categoria.objects.all()
    resultados['categorias'] = categorias

    if queryset:
        user = NewUser.objects.filter(username = queryset)
        resultados['posts'] = Post.objects.filter(
            Q(title__icontains = queryset) |
            Q(user__in = user)
        ).distinct()

    return render(request,'buscador.html', resultados)

def postCategoryView(request):

    categoria_id = request.GET.get('filtro', None)

    resultados = {}
    categorias = Categoria.objects.all()
    resultados['categorias'] = categorias

    if categoria_id:
        posteos = Post.objects.filter(categoria_id = categoria_id)
        resultados['posts'] = posteos 

    return render(request,'post/postCategory.html', resultados)

templates/post/postCategory.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  {{ block.super }}
   <link rel="stylesheet" type="text/css" href="{% static 'base/css/postCategory.css' %}">
{% endblock %}

{% block content %}
<div class="container mb-5">
    <div class="row">
        <div class="col-12">
            {% if posts %}
                <div class="d-flex justify-content-center mt-4" style="background-color: #303535; color: #FFFFFF;">
                    <h1>{{ posts.0.categoria }}</h1>
                </div>
                {% for post in posts %}
                    {% if forloop.first%}
                        <div class="row mt-4">
                    {% endif %}
                    <div class="col-4 mb-4">
                        <div class="card" style="background-color: #303535; color: #FFFFFF;">
                            {% if post.thumbnail %}
                                <img class="card-img-top" height="280" src="{{ post.thumbnail.url }}">
                            {% else %}
                                <img src="{% static 'base/img/ciudad.jpg' %}" class="card-img-top" height="280" alt="...">
                            {% endif %}
                            <div class="card-body" style="background-color: #303535; color: #FFFFFF;">
                                <h5 clas="card-title">{{ post.title }}</h5>
                                <h6 class="card-subtitle">Autor: {{ post.user }} </h6>
                                <p class="card-text">Categoría: {{ post.categoria }} </p>
                                <p class="card-text">Fecha: {{ post.publish_date }}</p>
                                <div class="card-body mt-2 d-flex justify-content-center">
                                    <a href="{% url 'posts:mostrarPost' post.id %}" class="btn btn-primary">Ir al post</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% if forloop.counter|divisibleby:3 %}
                        </div><div class="row">
                    {% endif%}

                    {% if forloop.last %}
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="alert alert-danger mt-4">No hay nada acá</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/post/postComment.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'post/css/postCommentForm.css' %}">
{% endblock %}

{% block content %}
    <div class="col-12 mb-4">
        <small><strong>{{ comment.user.username }} - {{ comment.timestamp }}</strong></small>
        <br/>
        {{ comment.content|linebreaks }}
    </div>
{% endblock %}

templates/post/postCommentForm.html
{% extends 'base.html' %}
{% load static %}

<!-- AGREGO EL TITULO DEL TEMPLATE-->


{% load crispy_forms_tags %}

{% block css %}
    {{ block.super }}
     <link rel="stylesheet" type="text/css" href="{% static 'post/css/post.css' %}">
{% endblock %}



{% block content %}
<div class="container comentario">
    <div class="row cuerpo rounded">
        <div class="col-12 item mt-5 mb-5">
            <form method="post" class="text-white">
                {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-12">
                            {{ form.content|as_crispy_field }}                            
                        </div>
                    </div>
                <button type="submit" class="btn btn-dark mt-5 btn-lg btn-block mb-4" value="CREAR COMENTARIO">CREAR COMENTARIO</button>   
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/post/postEdit.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block css %}
	{{ block.super }}
	 <link rel="stylesheet" type="text/css" href="{% static 'post/css/postEdit.css' %}">
{% endblock %}

 
{% block content %}
<div class="d-flex justify-content-center">
	<div class="container mt-5 mb-5 row cuerpo rounded " id="post_contenido">
		<div class="col-12 item">
			<form method="post" class="text-white" enctype="multipart/form-data">
				{% csrf_token %}
				
				<div class="form-row mt-4">
						<div class="form-group col-12">
							{{ form.title |as_crispy_field }}
						</div>
					</div>

					<div class="form-row">
						<div class="form-group col-12">
							{{ form.thumbnail |as_crispy_field }}
						</div>
					</div>

					<div class="form-row">
						<div class="form-group col-12">
							{{ form.content |as_crispy_field }}
						</div>
					</div>
					<div class="form-row">
						<div class="form-group col-12">
							{{ form.categoria |as_crispy_field }}
						</div>
					</div>

				<button type="submit" class="btn btn-light mt-5 btn-lg btn-block mb-4" value="CREAR POST">MODIFICAR POST</button>   
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/post/postForm.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'post/css/postForm.css' %}">
{% endblock %}

{% block content %}
<div class="row rounded">
    <div class="col-12 item mb-5" id="container-form">
        <form method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}

            <div class="form-row mt-4">
                <div class="form-group col-12">
                    {{ form.title | as_crispy_field }}
                </div>
            </div>

            <div class="form-row mt-2">
                <div class="form-group col-12">
                    {{ form.thumbnail | as_crispy_field }}
                </div>
            </div>

            <div class="form-row mt-2">
                <div class="form-group col-12">
                    {{ form.content | as_crispy_field }}
                </div>
            </div>

            <div class="form-row mt-2">
                <div class="form-group col-12">
                    {{ form.categoria | as_crispy_field }}
                </div>
            </div>

            <button type="submit" class="btn btn-outline-primary btn-lg btn-block mb-4 mt-4" value="CREAR POST">CREAR POST</button>
        </form>
    </div>
</div>
{% endblock %}

templates/post/postList.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'post/css/postList.css' %}">
{% endblock %}

{% block content %}
<div class="container mb-5">
    <div class="row">
        <div class="col-12">
            <div class="mt-5 d-flex justify-content-end">
                <form method="get">
                    <div name="select" value = "{{ request.GET.select }}">
                        <a href="{% url 'posts:listarPost2' %}" type="submit" class="btn btn-outline-light">Ordenar por comentario</a>
                    </div>
                </form>
            </div>
            {% if posts %}
                {% for post in posts %}
                    {% if forloop.first%}<div class="row">{% endif %}
                    <div class="col-4">
                        <div class="card mt-5" style="background-color: #303535; color: #FFFFFF;">
                            {% if post.thumbnail %}
                                <img class="" height="280" src="{{ post.thumbnail.url }}">
                            {% else %}
                                <img src="{% static 'base/img/ciudad.jpg' %}" height="280" class="" alt="...">
                            {% endif %}
                            <div class="card-body" style="background-color: #303535; color: #FFFFFF;">
                                <h5 clas="card-title">{{ post.title }}</h5>
                                <h6 class="card-subtitle">Autor: {{ post.user }} </h6>
                                <p class="card-text">Categoría: {{ post.categoria.nombre }} </p>
                                <p class="card-text">Fecha: {{ post.publish_date }}</p>
                                <div class="card-body mt-2 d-flex justify-content-center">
                                    <a href="{% url 'posts:mostrarPost' post.id %}" class="btn btn-primary">Ir al post</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:3 %} </div><div class="row">{% endif%}
                    {% if forloop.last %}</div>{% endif %}
                {% endfor %}

            {% else %}
                <div class="alert alert-danger">No hay nada acá</div>
            {% endif %}
        </div>
    </div>
</div>  
{% endblock %}

templates/post/postShow.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'post/css/postShow.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="container d-flex mt-3 mb-2 justify-content-center" id="post_contenido">
            <h2 class="card-header" style="color: #FFFFFF">{{ object.title }}</h2>
        </div>
    </div>
    <div class="row">
        <div class="container col-9 mb-4" id="post_contenido">
            <div class="container mb-3 mt-3 d-flex justify-content-end">
                <p><b>Post creado por {{ object.user.username }} - {{ object.publish_date }}</b></p>
            </div>
            <div class="mt-1 mb-2">
                <p>{{ object.content|safe }}</p>
                <div class="d-flex justify-content-center pt-4 pb-4">
                    {% if object.thumbnail %}
                        <img class="img-thumbnail" src="{{ object.thumbnail.url }}" alt="">
                    {% endif %}
                </div>
            </div>
            <div class="mt-5 mb-3">
                <div class="row">
                    {% if not user.is_authenticated %}
                        <div class="alert alert-primary">¿Te gustó lo que viste? Inicia sesión y dejanos un Like</div>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <form class="col d-flex justify-content-center" method="post" action="{% url 'posts:likesPost' post.id %}">
                            {% csrf_token %}
                            <button type="submit" value="{{ post.id }}" name="post_id" class="btn btn-outline-warning">Me gusta</button>
                        </form>
                        <form class="col d-flex justify-content-center" method="post" action="{% url 'posts:dislikesPost' post.id %}">
                            {% csrf_token %}
                            <button type="submit" value="{{ post.id }}" name="post_id" class="btn btn-outline-danger">No me gusta</button>                           
                        </form>
                        <div class="col d-flex justify-content-center">     
                            <a class="btn btn-outline-info" href="{% url 'posts:nuevoComentario' post.pk %}">Comentar</a>                           
                        </div>

                        <div class="col-6 mt-1 d-flex justify-content-end">
                            <b class="me-2">{{ object.total_likes }} LIKES</b>
                            <b class="ms-2">{{ object.total_dislikes }} DISLIKES</b>
                        </div>

                    {% else %}
                        <div class="mt-1 d-flex justify-content-end">
                            <b class="me-2">{{ object.total_likes }} LIKES</b>
                            <b class="ms-2">{{ object.total_dislikes }} DISLIKES</b>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="container col-3 mb-4 justify-content-center" id="post_contenido">
            <div class="row">
                {% if user.id == post.user.id %}
                    <form class="col-5 justify-content-center mt-3" method="post" action="{% url 'posts:deletePost' post.id %}">
                        {% csrf_token %}
                        <button type="submit" value="Comfirm" class="me-4 btn btn-outline-danger">
                            <b>ELIMINAR</b>
                        </button>
                    </form>
                    <div class="col-5 justify-content-center mt-3" >
                        <a href="{% url 'posts:editarPost' post.id %}" type="submit" value="Comfirm" class="btn btn-outline-warning">
                            <b>Editar</b>
                        </a>
                    </div>
            
                {% elif user.is_superuser %}
                    <form class="ms-1 me-1" method="post" action="{% url 'posts:deletePost' post.id %}">
                        {% csrf_token %}
                        <button type="submit" value="Comfirm" class="btn btn-outline-danger btn-sm">
                            <b>ELIMINAR</b>
                        </button>
                    </form>
                {% endif %}
                <div>
                    {% if object.user.image %}
                        <img class="img-thumbnail rounded mt-4" src="{{ object.user.image.url }}"></img>
                    {% else %}
                        <img class="img-thumbnail rounded mt-4" src="{% static 'usuario/imagen/Avatar.jpg' %}"></img>
                    {% endif %}
        
                    <div class="d-flex justify-content-center mt-4">
                        <h4>{{ object.user.username }}</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row mb-5" id="ComentariosContenido">
        <div class="mt-3 mb-3">
            <h4 id="tituloComentarios">COMENTARIOS:</h4>
        </div>
        {% if object.commentsPost.all %}
            {% for p in object.commentsPost.all %}
                <div class="col-12 mb-2">
                    <small><strong>{{ p.user.username }} - {{ p.timestamp }}</strong></small>
                    <br/>
                    {{ p.content|linebreaks }}
                    <hr/>
                </div>
            {% endfor %}    
        {% else %}
           {% if user.is_authenticated %}      
                <div class="alert alert-danger">No hay comentarios aún, ¡sé el primero en comentar!</div> 
            {% else %}
                <div class="alert alert-danger">Para ver y poder comentar, tienes que Iniciar Sesión!</div> 
            {% endif %}          
        {% endif %}
    </div>
</div>
{% endblock %}

templates/post/postSuccess.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'post/css/postSuccess.css' %}">
{% endblock %}

{% block content %}

<p>Post creado satisfactoriamente!!</p>

{% endblock %}